CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) NOT NULL,
    email varchar(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar NOT NULL,
    requestor_id bigint REFERENCES users(id) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) NOT NULL,
    description varchar NOT NULL,
    is_available boolean NOT NULL,
    owner_id bigint REFERENCES users(id) NOT NULL,
    request_id bigint REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id bigint REFERENCES items(id) NOT NULL,
    booker_id bigint REFERENCES users(id) NOT NULL,
    status varchar
);


CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar NOT NULL,
    item_id bigint REFERENCES items(id) NOT NULL,
    author_id bigint REFERENCES users(id) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);