CREATE TABLE IF NOT EXISTS users (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(256) NOT NULL,
	email varchar(512) UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(256),
	description varchar,
	available boolean,
	owner_id bigint REFERENCES users(id)
);